name: gateware-release

on:
  push:
    tags:
      - gateware-*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install OSS CAD Suite
        uses: YosysHQ/setup-oss-cad-suite@v2
        with:
          osscadsuite-version: '2023-05-05'

      - name: Build gateware
        run: |
          DISTDIR="reDIP-SID-${GITHUB_REF_NAME}"
          mkdir $DISTDIR
          make -C gateware
          cp -p gateware/README.md gateware/Pipelining.md gateware/flash.bat gateware/flash.sh gateware/redip_sid.bin $DISTDIR
          tar -czvf $DISTDIR.tar.gz $DISTDIR
          zip -r $DISTDIR.zip $DISTDIR

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            reDIP-SID*.tar.gz
            reDIP-SID*.zip
